name: release
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled

jobs:
  release:
    if: ${{ github.event.action != 'labeled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        uses: haya14busa/action-bumpr@v1
        dry_run: true

      # build the Docker Image
      - name:
        if: "${{ !steps.bumpr.outputs.skip }}"
        run: |
          ./.github/build.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          INPUT_TAG: ${{ steps.bumpr.outputs.next_version }}

      # Create release.
      - uses: shogo82148/actions-create-release@v1
        if: "${{ !steps.bumpr.outputs.skip }}"
        with:
          tag_name: ${{ steps.bumpr.outputs.next_version }}
          release_name: Release ${{ steps.bumpr.outputs.next_version }}
          body: ${{ steps.bumpr.outputs.message }}
          draft: false
          prerelease: false

  release-check:
    if: "${{ github.event.action == 'labeled' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
