
name: reviewdog
on: [pull_request]
jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionlint
        uses: ./
        with:
          actionlint_flags: examples/broken-workflow.yml
          tool_name: actionlint

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionlint w/ shellcheck
        uses: ./
        with:
          actionlint_flags: examples/shellcheck.yml
          tool_name: shellcheck

  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionlint w/ pyflakes
        uses: ./
        with:
          actionlint_flags: examples/pyflakes.yml
          tool_name: pyflakes
